### ISSUE TITLE
Feature Request: Migrate to Caido Native Plugin Support

### ISSUE THREAD

**Issue by Rhynorater** [bebiksior/EvenBetterExtensions#1]
Would it be possible to use the Even Better Extension store to add plugins which will be added to the `Plugins` tab?

**Comment by bebiksior** [comment]
Hey! I'm working on it. The next version will be out next week. I had to rework the extensions plugin to fit the new Caido plugin system

**Comment by bebiksior** [comment]
done in v2.4 :D
